# Generated by Django 4.2.6 on 2024-06-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_coupon_code"),
        ("orders", "0008_alter_cart_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                through="orders.CartItem", to="products.product"
            ),
        ),
    ]
