# Generated by Django 4.2.6 on 2024-06-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_coupon_code"),
        ("orders", "0009_cart_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="items", through="orders.CartItem", to="products.product"
            ),
        ),
    ]
