# Generated by Django 4.2.6 on 2024-06-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_remove_cart_customer_cart_user_alter_cart_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
