# Generated by Django 4.2.6 on 2024-02-04 17:52
from typing import List, Tuple

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Tuple[str, str]] = [
        ('auth', '0001_initial'),
        ('contenttypes', '0001_initial'),
        # Other dependencies...
    ]

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pharmacy_images/"
                    ),
                ),
                ("open_time", models.TimeField(default="00:00:00")),
                ("close_time", models.TimeField(default="00:00:00")),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
