# Generated by Django 4.2.6 on 2023-11-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_images/'),
        ),
    ]
