# Generated by Django 4.2.6 on 2024-02-23 18:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_pharmacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
