# Generated by Django 4.2.6 on 2024-06-20 20:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="pharmacy_images/"
                    ),
                ),
                ("open_time", models.TimeField(default="00:00:00")),
                ("close_time", models.TimeField(default="00:00:00")),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
