# Generated by Django 4.2.6 on 2024-02-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Africa/Cairo', max_length=50),
        ),
    ]
