import os
from unittest.mock import patch

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.files.uploadedfile import SimpleUploadedFile
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase
from rest_framework_simplejwt.tokens import RefreshToken

from accounts.models import *

User=get_user_model()
# testcase

# testcase


class UserProfileTest(APITestCase):
    def setUp(self):
        self.user_data = {
            "username": "testuser",
            "email": "test@example.com",
            "password1": "testpassword",
            "password2": "testpassword",
            "first_name": "test",
            "last_name": "test",
            "gender": "male",
        }
        self.profile_data = {
            "first_name": "John",
            "last_name": "Doe",
            "bio": "This is a test bio.",
            "date_of_birth": "1990-01-01",
            "gender": "Male",
        }

        # Create a user and obtain a token for authentication
        url = reverse("rest_register")
        self.client.post(url, self.user_data, format="json")

        self.user = User.objects.get(email=self.user_data["email"])
        # self.user = User.objects.create_user(**self.user_data)
        refresh = RefreshToken.for_user(self.user)
        self.access_token = str(refresh.access_token)
        # profile_id=self.user.profile.id
        # print("hhh")
        # print(profile_id)
        # Set the Authorization header with the token
        # self.client.credentials(HTTP_AUTHORIZATION='Token ' + self.token.key)

    def test_update_user_profile_without_token(self):
        # pass
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id
        response = self.client.put(url, self.profile_data, format="json")

        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def teste_update_user_profile_with_invalid_token(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}invalid")
        response = self.client.put(url, self.profile_data, format="json")
        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)

    def test_update_user_profile(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id

        # Set the Authorization header with the token
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")

        response = self.client.put(url, self.profile_data, format="json")
        # print(response.data)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_updata_image(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.put(url, self.profile_data, format="json")
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    # --------
    @patch("accounts.views.Profile.objects.get")
    @patch("accounts.views.ProfileSerializer")
    def test_update_profile(self, mock_serializer, mock_get):
        # Mocking the behavior of the serializer
        mock_serializer.return_value = None

        # Mocking the behavior of the get method
        mock_get.return_value = self.user.profile

        updated_data = {"first_name": "New First Name"}

        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        response = self.client.patch(url, updated_data, format="json")

        self.assertEqual(response.status_code, status.HTTP_200_OK)

    # @patch('accounts.views.Profile.objects.get')
    # @patch('accounts.views.ProfileSerializer')
    # def test_update_profile(self, mock_serializer, mock_get):
    #     # Mocking the behavior of the serializer
    #     mock_serializer.return_value = None

    #     # Mocking the behavior of the get method
    #     mock_get.return_value = self.user.profile

    #     updated_data = {
    #         'first_name': 'New First Name',
    #         'image': 'base64_encoded_image_data_here',  # Example: 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQE...'
    #         # Add other fields you want to update
    #     }

    #     self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.access_token}')
    # url = reverse('profile-detail', args=[self.user.profile.id])  # Assuming 'profile-detail' is the name generated by the router
    # response = self.client.patch(url, updated_data, format='json')
    # print(response.data)
    # self.assertEqual(response.status_code, status.HTTP_200_OK)

    # def test_retrieve_image(self):
    #     # Assuming 'profile-detail' is the name generated by the router
    #     url = reverse('profile-detail', args=[self.user.profile.id])
    #     self.profile_data['user'] = self.user.id
    #     self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.access_token}')

    #     # Create a mock image file
    #     mock_image = SimpleUploadedFile("test_image.jpg", b"file_content", content_type="image/jpeg")

    #     # Set the profile image to the mock image
    #     with patch('accounts.models.Profile.image', mock_image):  # Replace 'path.to.your.Profile' with the actual path to your Profile model
    #         # Send a PUT request to update the profile with the mock image data
    #         response = self.client.put(url, self.profile_data, format='multipart')
    #     self.assertEqual(response.status_code, status.HTTP_200_OK)

    # # Now, retrieve the profile to check if the image is returned correctly
    # response = self.client.get(url)
    # self.assertEqual(response.status_code, status.HTTP_200_OK)

    # # Ensure that the image data returned matches the mock image
    # self.assertIn('image', response.data)  # Assuming your API returns the image data under the 'image' key
    # self.assertIsNotNone(response.data['image'])

    # def test_image_field_upload(self):
    #     url = reverse('profile-detail', args=[self.user.profile.id])
    #     self.profile_data['user'] = self.user.id
    #     self.client.credentials(HTTP_AUTHORIZATION=f'Bearer {self.access_token}')

    #     mock_image = SimpleUploadedFile("image.jpg", b"file_content", content_type="image/jpeg")

    #     with patch('accounts.models.Profile.image', mock_image):  # Replace 'path.to.your.Profile' with the actual path to your Profile model
    #         response = self.client.put(url, self.profile_data, format='json')

    #         self.assertEqual(response.status_code, status.HTTP_200_OK)

    #     response = self.client.get(url)
    #     self.assertEqual(response.status_code, status.HTTP_200_OK)

    #     self.assertIn('image', response.data)  # Assuming your API returns the image data under the 'image' key
    # self.assertEqual(response.data['image'].name, 'image.jpg')  # Ensure the
    # correct image name is returned

    # --------

    def test_update_user_profile_without_profile(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id + '1000']
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.put(url, self.profile_data, format="json")
        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)

    def test_update_user_profile_without_user(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id + '1000'
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.put(url, self.profile_data, format="json")
        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_delete_user_profile(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.delete(url)
        self.assertEqual(response.status_code, status.HTTP_204_NO_CONTENT)

    def test_get_user_profile(self):
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        self.profile_data["user"] = self.user.id
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_get_user_profiles(self):
        url = reverse("profile-list")
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.get(url)
        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_filters_by_user_id(self):
        url = reverse("rest_register")
        for i in range(30):
            self.client.post(url, self.user_data, format="json")

        url = "/accounts/profile/"
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        response = self.client.get(url, {"user__id": self.user.id})
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(len(response.data), 1)
        response = self.client.get(url, {"user__id": "10100"})
        self.assertEqual(len(response.data), 0)


class MockingProfileTest(APITestCase):
    def setUp(self):
        self.user_data = {
            "username": "testuser",
            "email": "test@example.com",
            "password1": "testpassword",
            "password2": "testpassword",
            "first_name": "test",
            "last_name": "test",
            "gender": "male",
        }
        self.profile_data = {
            "first_name": "John",
            "last_name": "Doe",
            "bio": "This is a test bio.",
            "date_of_birth": "1990-01-01",
            "gender": "Male",
        }

        url = reverse("rest_register")
        self.client.post(url, self.user_data, format="json")

        self.user = User.objects.get(email=self.user_data["email"])
        refresh = RefreshToken.for_user(self.user)
        self.access_token = str(refresh.access_token)
        self.image = (
            b"\x47\x49\x46\x38\x39\x61\x01\x00\x01\x00\x00\x00\x00\x21\xf9\x04"
            b"\x01\x0a\x00\x01\x00\x2c\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02"
            b"\x02\x4c\x01\x00\x3b"
        )

    @patch("django.core.files.storage.FileSystemStorage._save")
    def test_serializer_contains_expected_fields(
        self,
        mock_save,
    ):
        mock_save.return_value = (
            "test_profile.jpg"  # Mocking the save method to return the expected value
        )

        updated_data = {
            "profile_image": SimpleUploadedFile(
                name="test_profile.jpg",
                content=b"mock image data",
                content_type="image/jpeg",
            )
        }

        # Assuming self.client is an instance of APIClient
        self.client.credentials(HTTP_AUTHORIZATION=f"Bearer {self.access_token}")
        url = reverse(
            "profile-detail", args=[self.user.profile.id]
        )  # Assuming 'profile-detail' is the name generated by the router
        response = self.client.patch(url, updated_data, format="multipart")

        self.assertEqual(response.status_code, status.HTTP_200_OK)

        response_profile = self.client.get(url).data
        self.user.profile.image = "default/user.jpg"
        self.assertEqual(self.user.profile.image, "default/user.jpg")
        data = {"image": None}
        response = self.client.patch(url, data, format="json")
        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response_profile["image"], "media/default/user.jpg")
        self.assertTrue(
            os.path.exists(os.path.join(settings.MEDIA_ROOT, "default/user.jpg"))
        )
