# Generated by Django 4.2.6 on 2024-06-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctor_patient_remove_patientprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="price_for_reservation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
