# Generated by Django 4.2.6 on 2024-06-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctor_location_doctor_price_for_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
