# Generated by Django 4.2.6 on 2024-07-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_remove_doctor_date_birth_remove_employee_date_birth_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
    ]
