# Generated by Django 4.2.6 on 2024-07-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctor_date_of_birth_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='emailverificationotp',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='emailverificationotp',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deleted_by_cascade',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='phonemodel',
            name='deleted_by_cascade',
        ),
    ]
