# Generated by Django 4.2.6 on 2024-07-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                default="percentage",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                default="percentage",
                max_length=10,
            ),
        ),
    ]
