# -*- coding: utf-8 -*-
# Generated by Django 4.2.6 on 2024-02-24 14:56

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon_number_coupon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=8, max_length=22, prefix='', unique=True),
        ),
    ]
