# Generated by Django 4.2.6 on 2024-06-18 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0006_alter_coupon_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productrating",
            old_name="comment",
            new_name="review",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="number",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="percentage",
        ),
        migrations.RemoveField(
            model_name="coupon",
            name="product",
        ),
        migrations.RemoveField(
            model_name="discount",
            name="percentage",
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="minimum_purchase_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="usage_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="coupon",
            name="usage_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="discount",
            name="discount_type",
            field=models.CharField(
                blank=True,
                choices=[("amount", "Amount"), ("percentage", "Percentage")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="wishlists", to="products.product"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="discount",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrating",
            unique_together={("user", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "name")},
        ),
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
    ]
