# Generated by Django 4.2.6 on 2024-06-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_comment_productrating_review_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantity",
            new_name="stock",
        ),
    ]
