# Generated by Django 4.2.6 on 2024-06-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_rename_quantity_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
