# Generated by Django 4.2.6 on 2024-07-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_wishlistitem_unique_together_wishlistitem_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
