# Generated by Django 4.2.6 on 2024-07-06 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_product_number_of_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pharmacy',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
