# Generated by Django 4.2.6 on 2024-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="conversation_images/"
            ),
        ),
    ]
