# Generated by Django 4.2.6 on 2024-07-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_deleted_and_more'),
        ('chat', '0002_conversation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='users',
        ),
        migrations.AddField(
            model_name='conversation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_conv', to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_conv', to='accounts.patient'),
        ),
    ]
