# Generated by Django 4.2.6 on 2024-06-21 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_rename_conservation_message_conversation_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Conservation",
            new_name="Conversation",
        ),
    ]
