# Generated by Django 4.2.6 on 2024-07-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_conversation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcmtoken',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messageseenstatus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageseenstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageSeenStatus',
        ),
    ]
