# Generated by Django 4.2.6 on 2024-07-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_deleted_and_more'),
        ('chat', '0005_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('doctor', 'patient')},
        ),
    ]
