# Generated by Django 4.2.6 on 2024-02-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='patient',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
