# Generated by Django 4.2.6 on 2024-02-23 13:28

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=20, prefix='', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=20, prefix='', primary_key=True, serialize=False, unique=True),
        ),
    ]
