# Generated by Django 4.2.6 on 2024-03-12 09:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymobOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paymob_order_id', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=False)),
                ('amount_cents', models.FloatField(default=0)),
                ('currency', models.CharField(default='EGP', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
