# Generated by Django 4.2.6 on 2023-11-09 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_profile_date_of_birth_profile_gender_patientprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the medication', max_length=255)),
                ('generic_name', models.CharField(help_text='Generic name of the medication', max_length=255)),
                ('form', models.CharField(help_text='Form of the medication (e.g., tablet, capsule, liquid)', max_length=255)),
                ('strength', models.CharField(help_text='Strength of the medication (e.g., 500mg)', max_length=255)),
                ('factory_company', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity of the product')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(help_text='Percentage of discount')),
                ('start_date', models.DateField(blank=True, help_text='Start date of the discount', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date of the discount', null=True)),
                ('product', models.ForeignKey(help_text='Product for which the discount is applicable', on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
