# Generated by Django 4.2.6 on 2023-11-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='productitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
