# Generated by Django 4.2.6 on 2024-02-06 12:03
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_quentity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="orders",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
