# Generated by Django 4.2.6 on 2024-02-16 21:24
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_productrating_comment_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quentity",
            new_name="quantity",
        ),
    ]
